library widget;

import 'dart:async';
import 'dart:math';
import 'dart:ui' show lerpDouble;

import 'package:base/base.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_svg/svg.dart';
import 'package:ginkgo_mobile/src/app.dart';
import 'package:ginkgo_mobile/src/blocs/auth/auth_bloc.dart';
import 'package:ginkgo_mobile/src/blocs/place_list/place_list_bloc.dart';
import 'package:ginkgo_mobile/src/models/models.dart';
import 'package:ginkgo_mobile/src/navigators.dart';
import 'package:ginkgo_mobile/src/screens/screens.dart';
import 'package:ginkgo_mobile/src/utils/assets.dart';
import 'package:ginkgo_mobile/src/utils/debouncer.dart';
import 'package:ginkgo_mobile/src/utils/designColor.dart';
import 'package:ginkgo_mobile/src/utils/gradientColor.dart';
import 'package:ginkgo_mobile/src/utils/strings.dart';
import 'package:ginkgo_mobile/src/widgets/errorWidgets/errorIndicator.dart';
import 'package:ginkgo_mobile/src/widgets/galleryItem.dart';
import 'package:ginkgo_mobile/src/widgets/gradientOutlineBorder.dart';
import 'package:ginkgo_mobile/src/widgets/spacingRow.dart';
import 'package:ginkgo_mobile/src/widgets/spincircle_bottom_bar/spincircle_bottom_bar.dart';
import 'package:ginkgo_mobile/src/widgets/tourWidgets/widgets/tourDetailWidget.dart';
import 'package:ginkgo_mobile/src/widgets/tourWidgets/widgets/tourInfoDetailWidget.dart';
import 'package:photo_view/photo_view.dart';
import 'package:photo_view/photo_view_gallery.dart';
import 'package:shimmer/shimmer.dart';
import 'package:sliding_sheet/sliding_sheet.dart';

export 'userWidgets/user_widgets.dart';

part 'addCommentWidget.dart';
part 'appBars/backAppBar.dart';
part 'avatar.dart';
part 'buttons/primaryButton.dart';
part 'containers/borderContainer.dart';
part 'containers/collapse_container.dart';
part 'customs/image_widget.dart';
part 'dialogs/photo_view_dialog.dart';
part 'gradientTextFormField.dart';
part 'gradientUnderlineBorder.dart';
part 'hiddenText.dart';
part 'loadingDotIndicator.dart';
part 'loadingIndicator.dart';
part 'placeWidgets/opacityPlace.dart';
part 'placeWidgets/place_bottom_sheet.dart';
part 'primaryScaffold.dart';
part 'rating.dart';
part 'skeleton.dart';
part 'tourWidgets/blackOpacityTour.dart';
part 'tourWidgets/tourItem.dart';
